export const mockProducts = [
  { id: '1',  images: [], name: 'Colar Ishtar',    description: 'Colar longo com pingente geométrico em aço inox 316L. 70 cm. Hipoalergênico, resiste à água e ao suor.',         price: 89.90,  category: 'Colares',   active: true, sort_order: 1,  image_url: null },
  { id: '2',  images: [], name: 'Colar Onça',      description: 'Colar curto com corrente mista e pingente animal print em aço inox. Antialérgico, não escurece.',                  price: 74.90,  category: 'Colares',   active: true, sort_order: 2,  image_url: null },
  { id: '3',  images: [], name: 'Colar Plêiades',  description: 'Conjunto de três correntes finas sobrepostas em aço inox escovado. Leveza máxima, inox grau cirúrgico.',          price: 69.90,  category: 'Colares',   active: true, sort_order: 3,  image_url: null },
  { id: '4',  images: [], name: 'Anel Lua',        description: 'Anel aberto ajustável com detalhe crescente lunar em aço inox 316L. Hipoalergênico, tamanho único.',              price: 44.90,  category: 'Anéis',     active: true, sort_order: 4,  image_url: null },
  { id: '5',  images: [], name: 'Anel Tigre',      description: 'Anel largo texturizado em aço inox escovado, inspirado em padrão natural. Resistente, antialérgico.',             price: 54.90,  category: 'Anéis',     active: true, sort_order: 5,  image_url: null },
  { id: '6',  images: [], name: 'Brinco Medusa',   description: 'Brinco de argola em aço inox com detalhe de argola fechada. Solda protegida, não oxida. Hipoalergênico.',         price: 59.90,  category: 'Brincos',   active: true, sort_order: 6,  image_url: null },
  { id: '7',  images: [], name: 'Brinco Star',     description: 'Brinco ear cuff estrela em aço inox com zircônia. Sem furo, pressão lateral. Leveza máxima.',                    price: 49.90,  category: 'Brincos',   active: true, sort_order: 7,  image_url: null },
  { id: '8',  images: [], name: 'Pulseira Nômade', description: 'Pulseira de elos quadrados em aço inox escovado. Fecho de lagosta. Inox 316L grau cirúrgico, não escurece.',     price: 64.90,  category: 'Pulseiras', active: true, sort_order: 8,  image_url: null },
  { id: '9',  images: [], name: 'Pulseira Orion',  description: 'Pulseira rígida com marcações em relevo em aço inox polido. Unissex. Hipoalergênico, resistente à oxidação.',     price: 79.90,  category: 'Pulseiras', active: true, sort_order: 9,  image_url: null },
  { id: '10', images: [], name: 'Kit Selvagem',    description: 'Colar Ishtar + Brinco Star em aço inox. Embalagem presente Babilônica. 5% de desconto no Pix.',                   price: 129.90, category: 'Kits',      active: true, sort_order: 10, image_url: null },
  { id: '11', images: [], name: 'Kit Babilônica',  description: 'Conjunto completo: colar + anel + brincos em aço inox coordenados. Embalagem premium. 5% desconto no Pix.',       price: 189.90, category: 'Kits',      active: true, sort_order: 11, image_url: null },
]
